sudo: required
language: bash
env:
  - DOKKU_VERSION=master
  - DOKKU_VERSION=v0.8.0
  - DOKKU_VERSION=v0.7.0
  - DOKKU_VERSION=v0.6.0
  - DOKKU_VERSION=v0.5.0
  - DOKKU_VERSION=v0.4.0
before_install:
  - sudo useradd -m dokku
  - make setup
  - sudo cp tests/bin/plugn /usr/local/bin/
  - sudo chown -R dokku tests/dokku
script: make test
